
#Ancient Classes Mod Client Configuration Settings
[gui]
	#Range: 0.0 ~ 1.0
	"Ability Bar Relative X" = 0.8125
	#Range: 0.0 ~ 1.0
	"Ability Bar Relative Y" = 1.0
	#Range: 0.0 ~ 30.0
	"Ability Bar Separation from center" = 10.0

